name: Tasker NextJS

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  tasker-ui:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Push to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd /var/www/ui.tasker.my.id
          sudo chown -R bagilink /var/www/ui.tasker.my.id
          git config --global --add safe.directory /var/www/ui.tasker.my.id
          git pull origin main
          npm install
          npm run build
          pm2 kill
          pm2 start npm --name "nextjs" -- start
          pm2 startup
          sudo chown -R www-data:www-data /var/www/ui.tasker.my.id
